Feature/split backend
htl-grieskirchen-core/core pull request #107
Opened 2022-11-16 10:44 UTC by Klausmd5

2022-11-16 15:03 UTC, profiluefter requested changes
Boa Änderungen bitte

2022-11-16 15:03 UTC, profiluefter commented on Core.Backend.Secure/Services/RsaService.cs
> +        rsa.ExportParameters(true);
Wos duad des? Konnst do an kommentar dazua doa?

2022-11-16 15:07 UTC, Klausmd5 commented on Core.Backend.Secure/Program.cs
> +    opt.AddPolicy("Admin", policy => policy.RequireClaim("rolle", "Admin"));
Wan dam id-token, ma kau owa a afoch mehrere polices verwendn

2022-11-16 15:08 UTC, profiluefter commented on Core.Backend.Secure/Program.cs
> +    opt.AddPolicy("Admin", policy => policy.RequireClaim("rolle", "Admin"));
Wonn donn auth token weil midn id token deafst nix mocha kinna weil der mehr oda weniger public is (weil na hoid de potentiell schiachn plugins hom)

2022-11-16 15:10 UTC, Klausmd5 commented on Core.Backend.Secure/Services/JwtService.cs
> +        if (user.GetType() == typeof(AuthToken))
GetType returnt owa in class name, damid is relativ egal.

2022-11-16 15:15 UTC, profiluefter commented on Core.Backend.Secure/Services/JwtService.cs
> +        if (user.GetType() == typeof(AuthToken))
Jo von mir aus, foid oba wenn ma a computed property mochan sowieso weg

2022-11-19 17:10 UTC, profiluefter requested changes

2022-11-19 17:10 UTC, profiluefter commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
this results in a string in the json and not in a nested json object

2022-11-19 17:10 UTC, profiluefter commented on Core.Backend.Secure/Program.cs
> +    });
des würd i eigentlich nu goaned definiern, weil a rolle admin gibts aktuell ned moi
(außerdem auth-token ned id-token)

2022-11-19 17:10 UTC, profiluefter commented on Core.Backend.Secure/Services/JwtService.cs
> +                : DateTime.Now.AddMinutes(Convert.ToInt32(_conf["ID-Token-Expiration"]));
i hätt einfoch gsogt user muas minuten eigebn ind config datei, des geht scho

2022-11-19 17:10 UTC, profiluefter commented on Core.Backend.Secure/Services/RsaService.cs
> +        rsa.ExportParameters(true);
laut de docs de du verlinkt host exportiert der des in den return wert von der methode, somit duad des so exakt goanix

2022-11-19 17:15 UTC, Klausmd5 commented on Core.Backend.Secure/Program.cs
> +    });
Is a example

2022-11-19 17:16 UTC, Klausmd5 commented on Core.Backend.Secure/Services/JwtService.cs
> +                : DateTime.Now.AddMinutes(Convert.ToInt32(_conf["ID-Token-Expiration"]));
Es is gstondn ds ane Tage und ds andane Minuten, und jz wiad da unterschied scho checkt

2022-11-19 17:16 UTC, profiluefter commented on Core.Backend.Secure/Program.cs
> +    });
brauch ma donn wonn scho im plugin template oda

2022-11-19 17:17 UTC, Klausmd5 commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
Des a normales json object, is mm. Fias frontend schena wie string splitten in TS

2022-11-19 17:19 UTC, profiluefter commented on Core.Backend.Secure/Services/JwtService.cs
> +                : DateTime.Now.AddMinutes(Convert.ToInt32(_conf["ID-Token-Expiration"]));
unkonventionell oba von mir aus

2022-11-19 17:20 UTC, profiluefter commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
wenns a normales objekt is konnst einfoch token.connectedPlatforms.includes("webuntis") mocha weil da gonze token gonz normal wie a json deserialisiert werdn konn im frontend

2022-11-19 17:24 UTC, Klausmd5 commented on Core.Backend.Secure/Program.cs
> +    });
is owa wuascht, wei wanstas ned im controller aktivierst, mochts nix

2022-11-19 17:27 UTC, Klausmd5 commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
des kannst so ah, und wanstas modular ois panele aufbaust kaustas so ohne splittn durchiteriern. Im notfoi mochst im frontend .join

2022-11-19 17:28 UTC, profiluefter commented on Core.Backend.Secure/Program.cs
> +    });
jo donn hoff ma moi dass se koana denkt "jo des brauch i" und ned weida drüba nochdemkt dass des de foische oat von token is, oba jo wird beim testen donn eh ned funktioniern

2022-11-19 17:29 UTC, Klausmd5 commented on Core.Backend.Secure/Services/RsaService.cs
> +        rsa.ExportParameters(true);
yeeted.

2022-11-19 17:30 UTC, profiluefter commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
gfoid ma ned oba laut internet gehts ned leicht ondas

2022-11-19 17:31 UTC, profiluefter approved these changes

2022-11-19 17:31 UTC, merged

2022-11-19 17:31 UTC, Klausmd5 commented on Core.Backend.Secure/Program.cs
> +    });
drum is eh id-token drunta, dan is eh 401

2022-11-19 17:32 UTC, Klausmd5 commented on Core.Backend.Secure/Program.cs
> +    });
bzw wies jz is gibts wsl a excepion xD

2022-11-19 17:35 UTC, Klausmd5 commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
i konn csv style mochn.. 

>  new Claim("connectedPlatforms", String.Join(",", ConnectedPlatforms)),

2022-11-19 17:36 UTC, Klausmd5 commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
owa indem dass da token sowieso a json obj is was egal

2022-11-19 17:39 UTC, Klausmd5 commented on Core.Backend.Secure/Auth/IDToken.cs
> +                new Claim("connectedPlatforms", JsonConvert.SerializeObject(ConnectedPlatforms)),
renamed to Admin-Example

2022-11-19 17:40 UTC, Klausmd5 commented on Core.Backend.Secure/Program.cs
> +    });
Admin-Example