move auth to lib
htl-grieskirchen-core/core pull request #131
Opened 2022-11-25 15:00 UTC by EinboeckFranz

2022-11-25 15:45 UTC, Klausmd5 submitted a review, later dismissed
Moch ma

2022-11-25 17:36 UTC, profiluefter requested changes

2022-11-25 17:36 UTC, profiluefter commented on Core.AuthLib/AuthConfigurator.cs
> +                options.RequireHttpsMetadata = false;
should be enabled

2022-11-25 17:36 UTC, profiluefter commented on Core.AuthLib/AuthConfigurator.cs
> +                        context.Token = context.Request.Cookies["Authorization"];
The plugin frontend can't send cookies!
For the plugin backend this has to be done with a header (and the Authorization header should be used)

So this should be configurable in the method parameters of AddAuth with a default value for plugin backends

2022-11-25 17:36 UTC, profiluefter commented on Core.AuthLib/AuthExtensions.cs
> +        => cp.Claims.First(x => x.Type.Contains("username")).Value;
Why is contains used here instead of a direct comparison?
Pretty standard way for such checks to become insecure.

2022-11-25 17:36 UTC, profiluefter commented on Core.AuthLib/Core.AuthLib.csproj
> +        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.0" />
Is newtonsoft JSON and Swashbuckle actually used somewhere?

2022-11-25 17:36 UTC, profiluefter commented on Core.AuthLib/Services/RsaService.cs
> +    public static RSA ImportRSAKey(string pem, bool isPk = false)
Does the secure backend still work? I don't think isPk=true is used anywhere

2022-11-25 17:40 UTC, EinboeckFranz commented on Core.AuthLib/AuthConfigurator.cs
> +                        context.Token = context.Request.Cookies["Authorization"];
@Klausmd5

2022-11-25 17:45 UTC, EinboeckFranz commented on Core.AuthLib/AuthExtensions.cs
> +        => cp.Claims.First(x => x.Type.Contains("username")).Value;
@Klausmd5

2022-11-25 17:48 UTC, Klausmd5 commented on Core.AuthLib/AuthConfigurator.cs
> +                        context.Token = context.Request.Cookies["Authorization"];
This lib is for Backend/Secure.There will be a override for plugins.

2022-11-25 17:49 UTC, Klausmd5 commented on Core.AuthLib/AuthExtensions.cs
> +        => cp.Claims.First(x => x.Type.Contains("username")).Value;
This was a leftover from the Microsoft schema where a URL was Provided.

2022-11-25 17:52 UTC, Klausmd5 commented on Core.AuthLib/Core.AuthLib.csproj
> +        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.0" />
Swashbuckle is needed for configuration.

2022-11-25 17:53 UTC, profiluefter commented on Core.AuthLib/Services/RsaService.cs
> +    public static RSA ImportRSAKey(string pem, bool isPk = false)
(also PK can mean both Private Key and Public Key so it should not be abbreviated)

2022-11-25 18:01 UTC, Klausmd5 commented on Core.AuthLib/AuthConfigurator.cs
> +                        context.Token = context.Request.Cookies["Authorization"];
@profiluefter Header = bearer?

2022-11-25 18:02 UTC, profiluefter commented on Core.AuthLib/AuthConfigurator.cs
> +                        context.Token = context.Request.Cookies["Authorization"];
The Header should be Authorization with a "Bearer" prefix in the value

2022-11-25 18:10 UTC, profiluefter commented on Core.AuthLib/AuthConfigurator.cs
> +        });
this duplicate code should of course be in a private method

2022-11-25 18:11 UTC, EinboeckFranz commented on Core.AuthLib/AuthConfigurator.cs
> +        });
@Klausmd5 mocht des.

2022-11-25 23:51 UTC, Klausmd5 commented on Core.AuthLib/Services/RsaService.cs
> +    public static RSA ImportRSAKey(string pem, bool isPk = false)
> Does the secure backend still work? I don't think isPk=true is used anywhere

na duads ned, liegt owa ned am isPK, sondan am einlesen.. riesige baustelle

2022-11-25 23:52 UTC, profiluefter commented on Core.AuthLib/Services/RsaService.cs
> +    public static RSA ImportRSAKey(string pem, bool isPk = false)
na seawas

2022-11-25 23:52 UTC, Klausmd5 commented
rsa eilesn is scheiße.

2022-11-25 23:54 UTC, Klausmd5 commented on Core.AuthLib/Services/RsaService.cs
> +    public static RSA ImportRSAKey(string pem, bool isPk = false)
jo wialki.. des hod jz a stund dauert :joy:

2022-11-25 23:56 UTC, profiluefter requested changes

2022-11-25 23:56 UTC, profiluefter commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
do woi ma header auth eigentlich, oda?

2022-11-25 23:56 UTC, Klausmd5 commented
@EinboeckFranz kaust ds midm plugin eventuell nu testn obs hin haut? Im prinzip muas owa, weis fost da söwe code is und nur nu im swagger pfuscht.

2022-11-25 23:57 UTC, Klausmd5 commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
na weils des normale core backend is oder?

2022-11-25 23:58 UTC, profiluefter commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
wo de plugins eineglodn weadn, jo

2022-11-26 00:00 UTC, Klausmd5 commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
mir egal, i änderts schnö

2022-11-26 00:08 UTC, Klausmd5 commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
oida..
oida..

`      An unhandled exception has occurred while executing the request.
      System.UnauthorizedAccessException: Access to the path '/home/klaus/Downloads/school/syp/core/Core.Backend/keys/' is denied.
`

2022-11-26 00:09 UTC, profiluefter commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
sponnend, `chmod -R 777 keys` und gemma hoffentlich

2022-11-26 00:09 UTC, Klausmd5 commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
wuascht, in da theorie miassads funktioniern

2022-11-26 00:10 UTC, Klausmd5 commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
> sponnend, `chmod -R 777 keys` und gemma hoffentlich

:joy: na, do hods glaubi gröber wos

2022-11-26 00:11 UTC, profiluefter approved these changes

2022-11-26 00:11 UTC, profiluefter commented on Core.Backend/Program.cs
> +builder.AddCookieAuth();
perfekt

2022-11-26 00:13 UTC, Klausmd5 approved these changes
jayjo sogt es bast

2022-11-26 00:13 UTC, Klausmd5 commented
> @EinboeckFranz kaust ds midm plugin eventuell nu testn obs hin haut? Im prinzip muas owa, weis fost da söwe code is und nur nu im swagger pfuscht.

wär mitm letzn commit eigentlich eh [Obsolete]

2022-11-26 00:13 UTC, merged