Feature/home component
htl-grieskirchen-core/core pull request #167
Opened 2022-12-12 09:28 UTC by seiflea

2022-12-12 10:23 UTC, littlegamer757 requested changes
Büda ned so speichern (discord frontend channel)

2022-12-12 10:23 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/home/home/home.component.ts
> +    this.getNewCategory('Favoriten', 'star.svg'),
de svgs so zu speichern finde ned optimal

2022-12-12 10:40 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/home/home/home.component.ts
> +    this.getNewCategory('Favoriten', 'star.svg'),
bast scho

2022-12-17 14:08 UTC, profiluefter requested changes
schauts vlt nu ob der oane import schena geht

code bast

2022-12-17 14:08 UTC, profiluefter commented on frontend/apps/frontend/src/app/home/home/home.component.ts
>  } from "../../../../../../libs/mainframe-connector/src/lib/mainframe-id-token.service";
from "mainframe-connector" soite funktioniern und bitte so benutzn (a wonns in der PR ned gändert woan is)

2022-12-18 16:41 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/home/home/home.component.ts
>  } from "../../../../../../libs/mainframe-connector/src/lib/mainframe-id-token.service";
i schätz moi d Lea wird des Mail ned lesn, miass ma ihr in da Schui morgen sogn

2022-12-18 17:01 UTC, Klausmd5 requested changes

2022-12-18 17:01 UTC, Klausmd5 commented on frontend/apps/frontend/src/app/home/category/category.component.ts
> +  plugins: Plugin[] = [
kinnts des ausm jwt lesn nu glei eini duan? Im prinzip muast nur in Janik sei lib aufruafn, da rest geht scho.

2022-12-18 17:05 UTC, profiluefter commented on frontend/apps/frontend/src/app/home/category/category.component.ts
> +  plugins: Plugin[] = [
im jwt stengan koane plugins drin

2022-12-18 17:29 UTC, Klausmd5 commented on frontend/apps/frontend/src/app/home/category/category.component.ts
> +  plugins: Plugin[] = [
Stimmt

2022-12-19 06:25 UTC, Klausmd5 submitted a review, later dismissed
Abfahrt.

2022-12-19 07:17 UTC, littlegamer757 submitted a review, later dismissed

2022-12-19 07:30 UTC, profiluefter approved these changes

2022-12-19 07:36 UTC, littlegamer757 approved these changes
oiso wonn da jayjo approved wirds scho passn

2022-12-19 07:37 UTC, Klausmd5 approved these changes

2022-12-19 07:41 UTC, merged