Feature/update mainframe
htl-grieskirchen-core/core pull request #170
Opened 2022-12-12 12:16 UTC by Klausmd5

2022-12-12 21:07 UTC, profiluefter requested changes

2022-12-13 08:49 UTC, Klausmd5 commented on frontend/libs/mainframe-connector/src/lib/mainframe-id-token.service.ts
> +      pluginId: "navigation",
I wass, wird aktuell ah ignoriert, owa wan de value 0 is schmeißt as aussi

2022-12-13 08:49 UTC, Klausmd5 commented on Core.Backend.Secure/Services/AuthService.cs
> +            .Where(x => x.GetValue(obj, null) is not null).Select(x => x.Name).ToList();
Maria, am dev is scho

2022-12-13 08:53 UTC, Klausmd5 commented on mainframe/index.html
>              clearFrameContainer("plugin-container");
Nix do, de Methode is suppa

2022-12-13 11:01 UTC, Klausmd5 commented
I muas des nur vor #167 mergen, sunst wirds schiach

2022-12-13 11:14 UTC, merged

2022-12-14 19:15 UTC, Klausmd5 commented
Closes #160