Create InputField components
htl-grieskirchen-core/core pull request #183
Opened 2022-12-19 08:19 UTC by TaWi04

2022-12-19 10:31 UTC, littlegamer757 commented
schau i ma nächste Woche moi on, konn ma ned so guad vorstöhn wie des donn hihaut

2022-12-29 17:42 UTC, Klausmd5 commented
> schau i ma nächste Woche moi on, konn ma ned so guad vorstöhn wie des donn hihaut

Host scho gschaud? Jo? Jo...
https://tenor.com/buRIB.gif

2022-12-29 18:23 UTC, littlegamer757 commented
Na, schau i ma nächste Woche moi on

2023-01-09 08:09 UTC, littlegamer757 requested changes

2023-01-09 08:09 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/email-input/email-input.component.html
> +         id="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
kinnan ma des mid tailwind stott css-id mochn? fande cooler, donn homma ned a extra file fia oan style

2023-01-09 08:09 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/password-input/password-input.component.html
> +         id="password"
do hätt i a gsogt de css-id mid tailwind ersetzn

2023-01-09 08:09 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/shared.module.ts
> +    RouterLink,
Des Modul wird ned hergnumma, weg damit (bitte)

2023-01-09 08:09 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/shared.module.ts
> +    FormsModule
des a ned

2023-01-09 08:09 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/app.module.ts
> +    RouterTestingModule
des modul konn ma weg doa weils ned benutzt wird

2023-01-23 07:25 UTC, ungarmichael commented
Wie schauma do aus? Is der PR nu relevant?

2023-01-23 18:55 UTC, littlegamer757 commented
so, schau ma si des moi on

2023-01-23 18:57 UTC, littlegamer757 commented
hoit, der PR geht aufd foische bránche, weil da Miks de core-ui-lib glöscht hod

2023-01-23 19:11 UTC, littlegamer757 commented
> Wie schauma do aus? Is der PR nu relevant?

der is nu relevant - oba ned auf develop, sondan auf core-ui-library

2023-01-23 19:12 UTC, merged