Provide list of plugins to frontend
htl-grieskirchen-core/core pull request #187
Opened 2022-12-19 09:28 UTC by SchneckchenAndy

Closes #159

2022-12-19 10:17 UTC, littlegamer757 requested changes
Brauchst goaned moana, dass i ma des ned onschau

2022-12-19 10:17 UTC, littlegamer757 commented on frontend/libs/mainframe-connector/src/lib/plugin-list-service.service.ts
> +export class PluginListServiceService {
HOLY SHIT WOS IS DES OIDA WIESO STHET DO ZWOAMOI SERVICE HEAST MOCH DES GSCHEID bitte

2022-12-19 10:17 UTC, littlegamer757 commented on frontend/libs/mainframe-connector/src/lib/plugin-list-service.service.ts
> +  public getPluginList(): Promise<Plugin[]> {
A Observable wa natürlich glass ne

2022-12-19 10:17 UTC, littlegamer757 commented on frontend/libs/mainframe-connector/src/lib/plugin.ts
> +    name: string | null,
name nicht nullable bitte (i woaß dass d Lena des pfuscht hod)

2022-12-19 10:17 UTC, littlegamer757 commented on frontend/libs/mainframe-connector/src/lib/plugin.ts
> +    tags: string[] | null,
i glaub des muass a ned null sein (danke Lena)

2022-12-19 10:52 UTC, Klausmd5 submitted a review, later dismissed

2022-12-19 10:52 UTC, Klausmd5 commented on mainframe/index.html
> +        const plugins = Object.entries(config.plugins).map(([name, plugin]) => {
map is jo moi a so geile implementation

2022-12-19 11:38 UTC, profiluefter requested changes

2022-12-19 11:38 UTC, profiluefter commented on mainframe/index.html
> +                case "getPluginList":
a `break` wa a ned schlecht, ne

2022-12-19 12:51 UTC, Klausmd5 commented on mainframe/index.html
> +                case "getPluginList":
Nix do! Ka pause

2022-12-19 17:08 UTC, littlegamer757 commented on mainframe/index.html
> +                case "getPluginList":
holy shit wieso is do im html a jovascript eigentlich

2022-12-19 17:08 UTC, littlegamer757 commented on mainframe/index.html
> +                case "getPluginList":
wir nemman Angular her, ned react!

2022-12-19 17:09 UTC, profiluefter commented on mainframe/index.html
> +                case "getPluginList":
des is as mainframe, des is ois oa file
woa mei geniale idee :)

2022-12-19 17:10 UTC, SchneckchenAndy commented on mainframe/index.html
> +                case "getPluginList":
Des nennt se Mainframe™ by Profilüfter

2022-12-19 17:13 UTC, SchneckchenAndy commented on mainframe/index.html
> +                case "getPluginList":
gottlos

2022-12-29 17:39 UTC, Klausmd5 commented
Passiert do aig moi wos herr aigner?!

2023-01-08 23:36 UTC, ungarmichael commented
wie schauma aus @SchneckchenAndy

2023-01-09 08:29 UTC, littlegamer757 requested changes
oiso so sicher ned

2023-01-09 08:29 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/home/home/home.component.ts
> +import {PluginListService} from "../../../../../../libs/mainframe-connector/src/lib/plugin-list.service";
der Import gfoit an @profiluefter sicher ned

2023-01-09 08:57 UTC, littlegamer757 submitted a review, later dismissed
sogn ma so

2023-01-09 08:57 UTC, SchneckchenAndy commented
> wie schauma aus @SchneckchenAndy

haud voi hi

2023-01-09 09:03 UTC, profiluefter approved these changes

2023-01-09 09:10 UTC, merged