Feature/list view
htl-grieskirchen-core/core pull request #188
Opened 2022-12-19 09:56 UTC by seiflea

2022-12-19 10:23 UTC, littlegamer757 requested changes
wird scho passn sunst

2022-12-19 10:23 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/home/dashboard/dashboard.component.ts
> +    this.courses = [
soit des ned vl categories hoaßn?

2022-12-19 10:23 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/home/list-view/list-view.component.ts
> +    this._plugins = [...this._plugins.sort((a,b) =>
brauch ma do den spread operator?

2022-12-19 10:28 UTC, littlegamer757 approved these changes
jo

2022-12-19 10:51 UTC, Klausmd5 commented
hods ned ghassn do wiad nu wos updated?

2022-12-19 11:42 UTC, profiluefter commented on frontend/apps/frontend/src/app/home/dashboard/dashboard.component.ts
> +import {Plugin} from "../../shared/classes/plugin";
mid dem import wirds probleme gebn soboid andi sei klumpat gemerged is konn i scho moi sogn

2022-12-19 11:44 UTC, profiluefter approved these changes

2022-12-19 12:01 UTC, seiflea commented on frontend/apps/frontend/src/app/home/dashboard/dashboard.component.ts
> +import {Plugin} from "../../shared/classes/plugin";
dem Plugin import?

2022-12-19 14:19 UTC, profiluefter commented on frontend/apps/frontend/src/app/home/dashboard/dashboard.component.ts
> +import {Plugin} from "../../shared/classes/plugin";
jo, wird ebn in #187 (EINS ACHT SIIIIEEEBEN) noch libs verschobn

2022-12-19 14:20 UTC, profiluefter commented on frontend/apps/frontend/src/app/home/dashboard/dashboard.component.ts
> +import {Plugin} from "../../shared/classes/plugin";
oba schaut eh aus ois ob de PR schnella gmerged wiad ois #187, oiso is' donn andi sei baustoi

2022-12-19 16:09 UTC, Klausmd5 approved these changes
Wan nix mea dazua kimt dan Abfahrt

2022-12-19 17:11 UTC, littlegamer757 commented
i merg de gaudi jetzt damid da Andi donn a Baustöh hod wonn #187 gemerged wird

2022-12-23 11:32 UTC, Klausmd5 commented
> i merg de gaudi jetzt damid da Andi donn a Baustöh hod wonn #187 gemerged wird

schaut iwi ned so aus :octocat:

2022-12-23 12:13 UTC, profiluefter commented
> > i merg de gaudi jetzt damid da Andi donn a Baustöh hod wonn #187 gemerged wird
> 
> schaut iwi ned so aus :octocat: 

CI soite beim Type Checken failen weils den Import nimma gibt

2022-12-23 12:19 UTC, profiluefter commented
Extra numoi CI rerunned (sogts es am andi ned 🤫) und entweder i versteh ned wie de CI funktioniert oda es foid donn ned ois auseinonda. Oba i glaub eher das i de CI ned gonz verstondn hob 😂

2022-12-29 13:54 UTC, merged

2022-12-29 13:54 UTC, profiluefter commented
des erklärt wieso do de CI ned komplett gefailed is

2022-12-29 17:38 UTC, Klausmd5 commented
> des erklärt wieso do de CI ned komplett gefailed is

Wos erklärts?

2022-12-29 17:46 UTC, profiluefter commented
> > des erklärt wieso do de CI ned komplett gefailed is
> 
> Wos erklärts?

jo wonn de PR nu ned moi gemerged woa konns schwa de CI von a ondan PR failen. Failed hoid trotzdem ned komischerweise