Implement WebUntis API
htl-grieskirchen-core/core pull request #193
Opened 2022-12-19 10:31 UTC by SchoenbergerFabian

ois wos nu ned geht is SIMON sei schuid (is deprecated olles)
fixes kemman hoffntlich irgndwonn numoi noch (sunst mua da Sickinger wida oruafn)

2022-12-19 10:33 UTC, SchoenbergerFabian commented
SIMON

2022-12-19 10:50 UTC, Klausmd5 requested changes

2022-12-19 10:50 UTC, Klausmd5 commented on Core.Backend.Secure/Services/WebUntisService.cs
> +            throw new NoSecretException();
NoSecretException() on Password

2022-12-19 10:50 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/ElementType.cs
> +public enum ElementType
Wos is des und wieso is hardcoded?

2022-12-19 10:50 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/Student.cs
> +    public string FirstName { get; set; }
Kennts do pls des mid = null!; initialisiern

2022-12-19 11:28 UTC, SchoenbergerFabian commented on Core.WebUntis.Interface/Types/ElementType.cs
> +public enum ElementType
Do gehts drum, TimeTables zun gettn und laut Simon han des de Werte dafia

2022-12-19 11:33 UTC, SchoenbergerFabian commented on Core.WebUntis.Interface/Types/ElementType.cs
> +public enum ElementType
TimeTable funktioniert is dawei sowieso deprecated bis da Simon moi hibringt

2022-12-19 11:34 UTC, SchoenbergerFabian commented on Core.WebUntis.Interface/Types/Student.cs
> +    public string FirstName { get; set; }
in olle Klassen im Types Folder?

2022-12-19 11:34 UTC, SchoenbergerFabian commented on Core.WebUntis.Interface/Types/Student.cs
> +    public string FirstName { get; set; }
@SturmTim @EliasAspoeck  @daFeichtl

2022-12-19 11:51 UTC, profiluefter commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
eigentlich woin wir de csv files ned unbedingt public im git hom

2022-12-19 11:59 UTC, profiluefter requested changes

2022-12-19 11:59 UTC, profiluefter commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +    [Obsolete("SIMON")]
wos soid uns des sogn?

2022-12-19 11:59 UTC, profiluefter commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +    //[Authorize(Policy = "Auth-Token")]
auskommentierter code schlecht

2022-12-19 11:59 UTC, profiluefter commented on Core.Backend.Secure/Services/CredService.cs
> +    public string? GetWebUntisSecret(Guid uuid) => DecryptPw(GetUserTokenSet(uuid).WebUntisSecret);
brauchn wir des webuntis secret jetzt übahaupt nu oda moch ma des eh midn ldap passwort?

2022-12-19 11:59 UTC, profiluefter commented on Core.Backend/Controllers/WeatherForecastController.cs
> +public class WeatherForecastController : Controller
wonn scho eher gonz weg

2022-12-19 11:59 UTC, profiluefter commented on Core.Backend/Core.Backend.csproj
> +      <Compile Remove="Controllers\WebUntisController.cs" />
is des obsicht?

2022-12-19 11:59 UTC, profiluefter commented on Core.Database/StoredUserTokens.cs
> +    public string? WebUntisSecret { get; set; }
brauch ma nimma, oda?

2022-12-19 11:59 UTC, profiluefter commented on Core.WebUntis.Implementation/Core.WebUntis.Implementation.csproj
> +      <PackageReference Include="AspNetCore.Totp" Version="2.3.0" />
wird des verwendet? wissat ned wo do a TOTP code vorkumma kunnt

2022-12-19 12:33 UTC, SchoenbergerFabian commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Wia sunst

2022-12-19 12:34 UTC, SchoenbergerFabian commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +    [Obsolete("SIMON")]
SIMON

2022-12-19 12:34 UTC, SchoenbergerFabian commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +    [Obsolete("SIMON")]
soid des sein vo da Pull Request description

2022-12-19 12:34 UTC, SchoenbergerFabian commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +    //[Authorize(Policy = "Auth-Token")]
des woa zua Erinnerung wie des gonga is, hob i uebasegn

2022-12-19 12:36 UTC, SchoenbergerFabian commented on Core.Backend/Controllers/WeatherForecastController.cs
> +public class WeatherForecastController : Controller
keine Ahnung wos do passiert is, i duas weg

2022-12-19 12:38 UTC, SchoenbergerFabian commented on Core.Backend/Core.Backend.csproj
> +      <Compile Remove="Controllers\WebUntisController.cs" />
Keine Ahnung wos ma dea do einehaut, i box moi weg

2022-12-19 12:39 UTC, SchoenbergerFabian commented on Core.WebUntis.Implementation/Core.WebUntis.Implementation.csproj
> +      <PackageReference Include="AspNetCore.Totp" Version="2.3.0" />
des wa ebnfois midn WebUntis Secret in Verwendung

2022-12-19 12:43 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/ElementType.cs
> +public enum ElementType
Ok, owa grundsätzlich sogt sa simon scho fü bledsinn.

2022-12-19 12:43 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/Student.cs
> +    public string FirstName { get; set; }
Jo olles wos hoid de ci markiert

2022-12-19 12:44 UTC, Klausmd5 commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Afoch des file ned einchecken, notfois moch ma a private repo

2022-12-19 12:45 UTC, Klausmd5 commented on Core.Backend.Secure/Services/CredService.cs
> +    public string? GetWebUntisSecret(Guid uuid) => DecryptPw(GetUserTokenSet(uuid).WebUntisSecret);
Najo i würds moi lossn und schaun wos damid Aufsich hod dass de afoch de api ändern

2022-12-19 12:56 UTC, SchoenbergerFabian commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Najo, es lest jo wos ausa, wead hoid nix geh?

2022-12-19 12:58 UTC, Klausmd5 commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Scho, owa wir woin ned de datn leakn wans ned sei muas. Außerdem wiad des jo jeds joa geändert wos im repo im Prinzip nix verlorn hod

2022-12-19 12:59 UTC, SchoenbergerFabian commented on Core.Backend.Secure/Services/CredService.cs
> +    public string? GetWebUntisSecret(Guid uuid) => DecryptPw(GetUserTokenSet(uuid).WebUntisSecret);
I hobs jetzt scho ausado, weil ma sowieso kane Infos vo WebUntis griagn

2022-12-19 14:10 UTC, profiluefter commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
na so persönliche daten kinna ma wirklich ned do public auf github lossn
soite wie da klaus scho schreibt entweder wie a config file behandelt wean oda wia hauns ind datenbank und mochn a CSV import schnittstelle oba des file miass ma aussa doa
bitte [wie do aus da commit history entferna](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#using-the-bfg) und donn miass ma am github support schreibn wie bei #167

2022-12-19 14:11 UTC, profiluefter commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
hob a nu ned gonz checkt wieso wir des file jetzt wirklich brauchn? wos hod des mid webuntis zduan? dass wir de permissions zum user auflisten ned hom hob i midgriagt oba wenn ma des jetzt eh ned übas webuntis mocha kinnan soite des eigentlich ned in da webuntis api sei

2022-12-19 14:14 UTC, profiluefter commented on Core.Backend.Secure/Services/CredService.cs
> +    public string? GetWebUntisSecret(Guid uuid) => DecryptPw(GetUserTokenSet(uuid).WebUntisSecret);
und des passwort wos ma eh scho hom benutzen is wahrscheinlich eh weniger fehleranfällig, oiso von do hea samma mid passwort glaub i eh guad dabei

2022-12-19 14:18 UTC, SchoenbergerFabian commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Des woa Angabe vom Grüneis

2022-12-19 14:19 UTC, SchoenbergerFabian commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Im Endeffekt hod ma do de IDs drin, de an ondre Stellen benötigt werdn

2022-12-19 16:03 UTC, Klausmd5 commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Es is zwoa sauber schiach owa wanses ned hi griagn wean mas so lossn miassn.  Des mid da DB wa wsl goaned so deppad, dan muasa ned jeds moi des file eilesn.

2022-12-19 16:09 UTC, SchoenbergerFabian commented on Core.Backend.Secure/CSV/students.csv
> +Klasse;Klassenvorstand;Familienname;Vorname;Email 1 (Schueler)
Don moch ma des so, hobs scho meine Leid mitgeteilt

2022-12-29 13:38 UTC, profiluefter requested changes
imma nu eigentlich-katastrophe

2022-12-29 13:54 UTC, CallMeAlasca requested changes

2022-12-29 13:54 UTC, CallMeAlasca commented on Core.WebUntis.Interface/Types/Timetable.cs
> +    //public string statflags { get; set; }
bitte glei wegdoa

2022-12-29 17:36 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/Timetable.cs
> +    //public string statflags { get; set; }
I glaub des is fum simon irgnd a unfertigs zeigs

2022-12-29 17:36 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/Timetable.cs
> +    //public string statflags { get; set; }
Is jo olles deprecated / auskommentiert

2022-12-29 17:50 UTC, EinboeckFranz commented on Core.WebUntis.Interface/Types/Timetable.cs
> +    //public string statflags { get; set; }
des schaut richtig nochn @daFeichtl aus

2023-01-10 20:32 UTC, profiluefter commented
Danke @EliasAspoeck dassd as CSV file wieda geadded host

guad gemerged

2023-01-11 05:27 UTC, EinboeckFranz commented
Große Katastrophe

2023-01-16 08:50 UTC, CallMeAlasca submitted a review, later dismissed

2023-01-16 09:21 UTC, Klausmd5 commented on Core.Backend.Secure/Services/CSVReaderService.cs
> +        IConfiguration conf
ia satz de anzign de an logger verwendn. lel

2023-01-16 09:35 UTC, Klausmd5 requested changes

2023-01-16 09:35 UTC, Klausmd5 commented on Core.Backend.Secure/Services/WebUntisService.cs
> +        var webUntisClient = new WebUntisClient("https://arche.webuntis.com", "htbla-grieskirchen", "Synopsis");
config biiiite

2023-01-16 09:35 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/ExamType.cs
> +[Obsolete("Deprecated due to unknown documentation")]
wos pasiert damid?

2023-01-16 09:35 UTC, Klausmd5 commented on Core.Backend.Secure/Services/CSVReaderService.cs
> +        IConfiguration conf
jo des passt soweit eh

2023-01-16 09:37 UTC, Klausmd5 commented on Core.WebUntis.Interface/Types/ExamType.cs
> +[Obsolete("Deprecated due to unknown documentation")]
de sochn entweder removen oder fertig mochn lossn

2023-01-16 14:56 UTC, ungarmichael commented
wonn wirdn des voraussichtlich moi gemerged?

2023-01-16 16:25 UTC, Klausmd5 commented
> wonn wirdn des voraussichtlich moi gemerged?

Boid

2023-01-16 16:44 UTC, profiluefter approved these changes

2023-01-16 16:44 UTC, profiluefter commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +public class WebUntisController : ControllerBase
konns sei dass der controller a Authorize attribut braucht weila aufn user zuagreift? und generell wahrscheinlich a ned bled de db zugriffe nur fia eigloggte user

2023-01-16 16:46 UTC, littlegamer757 commented
bist du deppad

2023-01-16 16:46 UTC, littlegamer757 approved these changes
oiso wonns da jayjo approved wirds scho passn

2023-01-16 16:47 UTC, Klausmd5 commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +public class WebUntisController : ControllerBase
> konns sei dass der controller a Authorize attribut braucht weila aufn user zuagreift? und generell wahrscheinlich a ned bled de db zugriffe nur fia eigloggte user

True, sunst prakts di auf.

2023-01-16 16:50 UTC, Klausmd5 requested changes
Wannts de annotations nu fixts und autorize addeds basts

2023-01-16 16:50 UTC, Klausmd5 commented on Core.Backend.Secure/Controllers/WebUntisController.cs
> +
Add 

> [Authorize]

2023-01-23 07:14 UTC, Klausmd5 submitted a review, later dismissed
i glaub des wird wos

2023-01-23 07:20 UTC, littlegamer757 approved these changes
Oiso wonn da Klausi sogt des wird wos

2023-01-23 07:24 UTC, ungarmichael commented
@Klausmd5 konn ma mergn oda?

2023-01-23 07:27 UTC, CallMeAlasca approved these changes

2023-01-23 10:44 UTC, profiluefter submitted a review, later dismissed

2023-01-23 12:06 UTC, EinboeckFranz approved these changes
Schaut guad aus vo meina Seitn

2023-01-23 18:52 UTC, littlegamer757 submitted a review, later dismissed
dass ma wos siagt a amoi

2023-01-23 19:02 UTC, profiluefter commented
> wonn wirdn des voraussichtlich moi gemerged?

@ungarmichael ma segt glaub i boid wos

2023-01-23 19:58 UTC, SchoenbergerFabian commented
So, merge conflict is resolved

2023-01-23 19:58 UTC, profiluefter approved these changes
bast sicha imma nu

2023-01-23 19:58 UTC, profiluefter commented
soi ma mergen?

2023-01-23 19:59 UTC, SchoenbergerFabian commented
I force do goa nix xD

2023-01-23 19:59 UTC, EinboeckFranz approved these changes
Seg i so wie da Jayjoe

2023-01-23 20:01 UTC, merged

2023-01-23 20:02 UTC, Klausmd5 commented
He oida des woit i grod mochn

2023-01-23 20:02 UTC, profiluefter commented
ha, ersta

2023-01-23 20:15 UTC, profiluefter commented
![](https://media.tenor.com/w0P0FSoo3z0AAAAC/pull-request-code.gif)

2023-01-23 20:25 UTC, littlegamer757 commented
"mochma team branches, is glaube gscheida"