Feature/nav bar
htl-grieskirchen-core/core pull request #230
Opened 2023-01-23 08:28 UTC by annalena-kagerer

2023-01-23 12:14 UTC, littlegamer757 requested changes
sunst passt glaube

2023-01-23 12:14 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.css
> +  border-radius: 25px;
kunnt ma vl mid rounded-full mochn, muass ma probieren

2023-01-23 12:14 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.css
> +::placeholder {
des moch ma a mid tailwind: https://tailwindcss.com/docs/hover-focus-and-other-states#placeholder-text

2023-01-28 21:09 UTC, annalena-kagerer commented on frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.css
> +  border-radius: 25px;
is gmocht

2023-01-28 23:14 UTC, littlegamer757 approved these changes
Passt

2023-01-28 23:18 UTC, littlegamer757 requested changes
Ansonsten passt

2023-01-28 23:18 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
> +  closeSearchBar() {
des is iwie doppelt, duad dessöbe wie searchClicked

2023-01-28 23:19 UTC, littlegamer757 commented
wait, wieso woit der zwoamoi mein review und wieso geht des überhaupt?

2023-01-29 15:17 UTC, littlegamer757 approved these changes
oiso i würd sogn des passt

2023-01-29 23:39 UTC, Klausmd5 commented
Wans bast dan basts. Wie scho ds Grüneis mand: Scheiß auf codereview.

2023-01-29 23:39 UTC, merged

2023-01-30 07:51 UTC, ungarmichael commented
> Wans bast dan basts. Wie scho ds Grüneis mand: Scheiß auf codereview.

I hätt scho nu wos gändat, oba is scho zspäd 😖

2023-01-30 07:54 UTC, ungarmichael commented
@Klausmd5 konn ma den branch recovern?