Feature/ldap
htl-grieskirchen-core/core pull request #26
Opened 2022-09-26 08:40 UTC by SandroGreinecker

Hallo Frano69! 
Hier der Code vom heutigen Pair-Programming.
Der Teamleiter und ich wünschen dir gute Besserung!

PUll reqquest wurde abgesandt von mhlugr

2022-09-26 09:36 UTC, EinboeckFranz requested changes
2 changes required

2022-09-26 09:36 UTC, EinboeckFranz commented on Core.Ldap.Implementation/LdapClient.cs
> +        var serverId = new LdapDirectoryIdentifier("10.10.0.11");
Local LDAP Server IP in global repository → Discuss with architecture team, if this should be changed. @htl-grieskirchen-core/architektur

2022-09-26 09:36 UTC, EinboeckFranz commented on Core.Ldap.Interface/SignInResult.cs
> +    public object User { get; set; } = null!;
User has object type, change before merging

2022-09-26 09:49 UTC, profiluefter commented on Core.Ldap.Implementation/LdapClient.cs
> +        var serverId = new LdapDirectoryIdentifier("10.10.0.11");
should be in appsettings.json injected via dependency injection
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#bind-hierarchical-configuration-data-using-the-options-pattern

2022-09-27 09:35 UTC, SandroGreinecker commented on Core.Ldap.Implementation/LdapClient.cs
> +        var serverId = new LdapDirectoryIdentifier("10.10.0.11");
jo mochma

2022-10-03 06:29 UTC, EinboeckFranz commented on Core.Ldap.Implementation/LdapClient.cs
> +        var serverId = new LdapDirectoryIdentifier("10.10.0.11");
Resolved in 751f1f63b768c07e61a77f29bd0ebe03532b413f

2022-10-03 06:35 UTC, profiluefter submitted a review, later dismissed
Pfeifs!

2022-10-04 08:12 UTC, profiluefter commented on Core.Ldap.Interface/LdapUser.cs
> +    public string OrganizationUnit { get; set; } = null!;
Could this also use the LdapGroup enum?

2022-10-04 09:15 UTC, EinboeckFranz commented on Core.Ldap.Interface/LdapUser.cs
> +    public string OrganizationUnit { get; set; } = null!;
Implemented in e097d04e3748c6b0171e9e2aae3903ec41f005b3.

2022-10-04 09:41 UTC, Klausmd5 commented on Core.Ldap.Interface/SignInResult.cs
> +    public object User { get; set; } = null!;
Outdated

2022-10-04 09:54 UTC, profiluefter submitted a review, later dismissed

2022-10-10 09:01 UTC, EinboeckFranz reviewed
fixed

2022-10-10 09:03 UTC, EinboeckFranz requested changes
Find a solution that works on Linux as well

2022-10-10 09:03 UTC, EinboeckFranz commented on Core.Ldap.Implementation/LdapClient.cs
> +        var request = new SearchRequest("DC=htl,DC=grieskirchen,DC=local",
Request throws exception on Linux, on Windows it somehow works

2022-10-10 09:29 UTC, EinboeckFranz commented on Core.Ldap.Implementation/LdapClient.cs
> +        var request = new SearchRequest("DC=htl,DC=grieskirchen,DC=local",
resolved in fcf6640db7b910966861bada79255f533c0b65c5

2022-10-10 09:31 UTC, EinboeckFranz approved these changes
works on both Linux and Windows

2022-10-10 10:36 UTC, profiluefter approved these changes

2022-10-10 10:37 UTC, EinboeckFranz approved these changes

2022-10-10 10:37 UTC, Klausmd5 approved these changes
whistles!

2022-10-10 10:38 UTC, merged