Feature/user favorites
htl-grieskirchen-core/core pull request #278
Opened 2023-02-06 09:20 UTC by SandroGreinecker

2023-02-06 09:48 UTC, EinboeckFranz requested changes

2023-02-06 09:48 UTC, EinboeckFranz commented on Core.Database/UserFavorite.cs
> +    public Guid UUID { get; set; }
Do wüad i fost an Foreign Key Constraint mochn

2023-02-06 09:48 UTC, EinboeckFranz commented on Core.Database/CoreContext.cs
> +    }
warum brauchts ihr des?

2023-02-06 09:55 UTC, Klausmd5 requested changes

2023-02-06 09:55 UTC, Klausmd5 commented on Core.Backend.Secure/Controllers/UserController.cs
```suggestion
[Authorize]
```

2023-02-06 09:55 UTC, Klausmd5 commented on Core.Backend.Secure/Services/UserService.cs
> +    public async Task<List<UserFavoriteDto>> GetUserFavorites()
I hätt do eig gern nur meine eigenen favourites... @profiluefter i glb wir miassn do wen blamen

2023-02-06 09:55 UTC, Klausmd5 commented on Core.Database/UserFavorite.cs
> +    public Guid UUID { get; set; }
jo owa des haut nur im modelbuilder hi.

2023-02-06 09:55 UTC, Klausmd5 commented on Core.Database/CoreContext.cs
> +        modelBuilder.Entity<UserFavorite>().HasKey(u => new
`b.HasIndex(new[] { "CompanyId", "CognitoId" }, "company_emp_pk")
                        .IsUnique();
`

2023-02-06 11:59 UTC, SandroGreinecker commented on Core.Database/CoreContext.cs
> +    }
brauch ma so weils sunst ned geht

2023-02-06 18:34 UTC, profiluefter requested changes

2023-02-06 18:34 UTC, profiluefter commented on Core.Backend.Secure/Services/UserService.cs
> +    public async Task<List<UserFavoriteDto>> GetUserFavorites()
wa scho praktisch gö

2023-02-06 18:34 UTC, profiluefter commented on Core.Backend.Secure/Services/UserService.cs
> +        return (await usr).Select(x => new UserFavoriteDto()
await bitte in da zeile drüba donn konnst da klammern spoan und es is fui übersichtlicher

2023-02-06 18:34 UTC, profiluefter commented on Core.Database/CoreContext.cs
> +        modelBuilder.Entity<UserFavorite>().HasKey(u => new
na des is deren composite primary key des bast

2023-02-06 18:34 UTC, profiluefter commented on Core.Database/CoreContext.cs
> +        modelBuilder.Entity<UserFavorite>().HasKey(u => new
aso du moanst zusätzlich an foreign key
jo des griagns scho hi

2023-02-06 18:34 UTC, profiluefter commented on Core.Database/UserFavorite.cs
> +    [Key, Column(Order = 0)]
brauch ma de `Key` und `Column` attributes? key wird eh im modelbuilder gsetzt und de column order is eigentlich gonz wuascht

2023-02-06 18:41 UTC, Klausmd5 commented on Core.Database/CoreContext.cs
> +        modelBuilder.Entity<UserFavorite>().HasKey(u => new
> aso du moanst zusätzlich an foreign key jo des griagns scho hi

Unique key, hama kane duplicates

2023-02-06 19:17 UTC, profiluefter commented on Core.Database/CoreContext.cs
> +        modelBuilder.Entity<UserFavorite>().HasKey(u => new
des wos jetzt im code steht is jo scho a primary key oda
und primary keys sand grundsätzlich scho moi unique

2023-02-13 08:21 UTC, SandroGreinecker commented on Core.Backend.Secure/Services/UserService.cs
> +    public async Task<List<UserFavoriteDto>> GetUserFavorites()
i woas

2023-02-27 08:43 UTC, SandroGreinecker commented on Core.Database/UserFavorite.cs
> +    [Key, Column(Order = 0)]
jo is wuascht

2023-03-02 11:16 UTC, Klausmd5 commented
![image](https://user-images.githubusercontent.com/44428493/222413471-82133eb2-7824-482d-bce9-e9e820aa8f63.png)

2023-03-06 07:16 UTC, EinboeckFranz submitted a review, later dismissed
dadurch das jetzt ausgmocht woadn is, dass de Guid ned auf User gechanged wiad schauts ok aus

2023-03-06 07:29 UTC, Klausmd5 requested changes
change

2023-03-06 07:29 UTC, Klausmd5 commented on Core.Backend.Secure/Dtos/UserFavoriteDto.cs
> +    public Guid UUID { get; set; }
foreign key .. https://www.entityframeworktutorial.net/code-first/foreignkey-dataannotations-attribute-in-code-first.aspx

2023-03-06 08:03 UTC, EinboeckFranz commented
move to "normal" Backend

2023-03-13 08:20 UTC, EinboeckFranz commented
![image](https://user-images.githubusercontent.com/71697706/224645110-26823ce5-869b-4733-9690-7ecc8f66972c.png)

2023-03-13 08:57 UTC, EinboeckFranz requested changes
bis auf den comment ok

2023-03-13 08:59 UTC, EinboeckFranz requested changes
jetzt oba ah mit comment

2023-03-13 08:59 UTC, EinboeckFranz commented on Core.Backend/Core.Backend.csproj
> +    </ItemGroup>
den comment hob i gmoant

2023-03-17 09:46 UTC, EinboeckFranz approved these changes
ok

2023-03-17 13:33 UTC, Klausmd5 approved these changes
Kunnt bassn

2023-03-17 15:10 UTC, profiluefter approved these changes

2023-03-20 06:44 UTC, merged