feature/core-UI-library
htl-grieskirchen-core/core pull request #281
Opened 2023-02-06 09:34 UTC by littlegamer757

2023-02-06 11:00 UTC, EinboeckFranz commented
![image](https://user-images.githubusercontent.com/71697706/216954895-5003c3c1-a744-4bad-8254-454a0f6878d0.png)

2023-02-06 11:45 UTC, littlegamer757 commented
scheiß deepsource deckt mein pfusch auf

2023-02-06 11:45 UTC, littlegamer757 commented
hob ma docht de inspection hobe scho deaktiviert

2023-02-13 08:03 UTC, ungarmichael commented
@EinboeckFranz du bist backend!

2023-03-02 11:16 UTC, Klausmd5 commented
![image](https://user-images.githubusercontent.com/44428493/222413471-82133eb2-7824-482d-bce9-e9e820aa8f63.png)

2023-03-20 09:14 UTC, profiluefter requested changes
Keat nu auf gscheide library usage umbaut

2023-03-20 09:14 UTC, profiluefter commented on frontend/apps/frontend/src/app/home/home/home.component.ts
> +import {SelectOption} from "../../../../../../libs/core-ui/src/lib/syno-select-multiple/syno-select-multiple.component";
illegal, des wa des ziel
```suggestion
import {SelectOption} from "core-ui";
```
keat in https://github.com/htl-grieskirchen-core/core/blob/develop/frontend/libs/core-ui/src/index.ts nu eitrogn damit do wos geht

2023-03-20 09:15 UTC, profiluefter commented on frontend/apps/frontend/src/app/home/home/home.component.ts
> +import {SelectOption} from "../../../../../../libs/core-ui/src/lib/syno-select-multiple/syno-select-multiple.component";
wo ma dabei sand de zeile 9 is a gonz sche cursed

2023-03-20 09:21 UTC, profiluefter approved these changes

2023-03-20 09:22 UTC, merged