Tests/webuntis
htl-grieskirchen-core/core pull request #289
Opened 2023-02-27 08:19 UTC by SturmTim

2023-02-27 08:42 UTC, profiluefter requested changes

2023-02-27 08:42 UTC, profiluefter commented on Core.WebUntis.Tests/UnitTest1.cs
> +    }
einfoch funktion aufruafn duad des söbe

2023-02-27 08:47 UTC, EliasAspoeck commented on Core.WebUntis.Tests/UnitTest1.cs
> +    }
Najo, wir hättn des hoid so gedocht, dass ma do jede Exception de ma griagn konn einzeln behandeln kunnt, weil des irgendwonn amoi da Plan woa.
Oba jo, so wies jz is mocht des wenig Sinn, woas a ned ob des generell Sinn mocht, weil de ErrorMessage von da Exception sogt da meistens eh scho wosd wissn muassd

2023-02-27 09:34 UTC, EliasAspoeck commented
Schaut guad aus

2023-02-27 19:04 UTC, profiluefter approved these changes

2023-03-02 11:16 UTC, Klausmd5 commented
![image](https://user-images.githubusercontent.com/44428493/222413471-82133eb2-7824-482d-bce9-e9e820aa8f63.png)

2023-03-06 07:02 UTC, merged