Feature/UI refactor
htl-grieskirchen-core/core pull request #295
Opened 2023-02-27 08:50 UTC by ungarmichael

2023-03-02 11:15 UTC, Klausmd5 commented
![image](https://user-images.githubusercontent.com/44428493/222413471-82133eb2-7824-482d-bce9-e9e820aa8f63.png)

2023-03-06 07:23 UTC, littlegamer757 requested changes
Ansonsten hätt i gsogt passt

2023-03-06 07:39 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/footer/footer.component.html
> +    <app-syno-btn>
mochma nochher

2023-03-06 07:40 UTC, littlegamer757 approved these changes

2023-03-06 07:40 UTC, merged