Fix/open tasks
htl-grieskirchen-core/core pull request #328
Opened 2023-03-20 08:09 UTC by ungarmichael

ui zeigs

2023-03-20 08:21 UTC, Klausmd5 requested changes

2023-03-20 08:21 UTC, Klausmd5 commented on frontend/apps/mainframe/public/mainframe-config.json
> +                "name": "Umfragen",
Do gibts a zweite config ah nu im deployment Ordner. De eigentlich wichtiger is wei de config do nur local is.

2023-04-16 10:25 UTC, EinboeckFranz commented on frontend/apps/mainframe/public/mainframe-config.json
> +                "name": "Umfragen",
resolved by @ungarmichael in https://github.com/htl-grieskirchen-core/core/pull/328/commits/3a663d2c9060c10ba6a336710d72f78af6de55f6

2023-04-17 06:09 UTC, profiluefter approved these changes

2023-04-17 13:14 UTC, profiluefter approved these changes
boa changes find i weng unnötig oba von mir aus

2023-04-17 13:15 UTC, profiluefter approved these changes
ok bast
(grod im posteingang gfundn 😂)

2023-04-17 13:18 UTC, EinboeckFranz commented
Olle guaden Dinge sand drei.

2023-04-17 14:34 UTC, littlegamer757 approved these changes
okay

2023-04-17 16:46 UTC, profiluefter approved these changes
normal

2023-04-17 17:13 UTC, Klausmd5 submitted a review, later dismissed
Wird scho bassn

2023-04-17 17:14 UTC, Klausmd5 commented
@EinboeckFranz ds mim automerge funktioniert eh ned wans nu conflicts gibt

2023-04-17 17:15 UTC, EinboeckFranz commented
Wuascht, hobn is bessa ois brauchn

2023-04-26 17:57 UTC, Klausmd5 commented on frontend/package.json
> +    "dev:auth": "nx serve auth",
ob des so legal is woas i ned

2023-04-26 17:59 UTC, merged