Update Settings
htl-grieskirchen-core/core pull request #334
Opened 2023-03-20 09:41 UTC by TaWi04

Add Tab
Remove buttons when selected

2023-03-21 13:39 UTC, littlegamer757 requested changes

2023-03-21 13:39 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/settings/settings.component.ts
> +    console.log(`Password: ${this.password}`)
woaß jo ned, ob des so a guade Idee is (Spoiler: is ned)

2023-03-21 13:39 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/settings/settings.component.ts
> +    console.log("click") //FUNKTIONIERT NED SO WIRKLE :(
soimas donn scho mergen?

2023-03-21 13:39 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
> +  settingsShown: boolean = false;
is ok, oba an sich kamad ma des schena vor, wonn ma sowos üban navbar-service mochad, fois des geht

2023-03-21 13:39 UTC, littlegamer757 commented on frontend/apps/mainframe/src/app/handler.ts
> +        isAllowed: context => context.sender === "auth" || context.sender === "navigation"
wieso genau is des do? kummt des von an merge?

2023-03-27 06:10 UTC, TaWi04 commented on frontend/apps/mainframe/src/app/handler.ts
> +        isAllowed: context => context.sender === "auth" || context.sender === "navigation"
braucht ma fias encrypten vom passwort fian login, hod da Gurtna gmocht

2023-03-27 06:11 UTC, TaWi04 commented on frontend/apps/frontend/src/app/settings/settings.component.ts
> +    console.log("click") //FUNKTIONIERT NED SO WIRKLE :(
waun ma des mim Settingstab hobn woin, kinn mas mergen, as einloggen funktioniert hoid dawei nu ned

2023-03-27 06:17 UTC, littlegamer757 commented on frontend/apps/mainframe/src/app/handler.ts
> +        isAllowed: context => context.sender === "auth" || context.sender === "navigation"
oke

2023-03-27 06:19 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/settings/settings.component.ts
> +    console.log("click") //FUNKTIONIERT NED SO WIRKLE :(
asou s Einloggen beim Webuntis mid de Credentials vom Settings-Screen geht ned, des is ok

2023-03-27 06:48 UTC, littlegamer757 requested changes
Ansonsten bast fia mi

2023-03-27 06:48 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
> +    if (plugin.id === "settings") this.navService.toggleAreSettingsShown()
Semikolon wa glass

2023-03-27 06:48 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
> +    this.navService.toggleAreSettingsShown()
Semikolon wa glass

2023-03-27 07:13 UTC, littlegamer757 approved these changes

2023-03-27 08:18 UTC, merged

2023-03-27 14:12 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/settings/settings.component.ts
> +import {CredService} from "../../../../auth/src/app/core/cred.service";
du mid deine libraries oiwei, soima fia des vl a nu a eigene Repo mochn? 😂

2023-03-27 14:14 UTC, profiluefter commented on frontend/apps/frontend/src/app/settings/settings.component.ts
> +import {CredService} from "../../../../auth/src/app/core/cred.service";
ois a gigantischer pfusch des projekt

2023-03-27 15:42 UTC, littlegamer757 commented on frontend/apps/frontend/src/app/settings/settings.component.ts
> +import {CredService} from "../../../../auth/src/app/core/cred.service";
wa eh gscheida