New deployment process
htl-grieskirchen-core/core pull request #358
Opened 2023-04-17 20:46 UTC by profiluefter

2023-04-18 11:36 UTC, Klausmd5 commented
Moved to [https://github.com/htl-grieskirchen-core/devops ](oida)

2023-04-20 12:45 UTC, Klausmd5 commented
> de CI miass ma trotzdem nu mergen

:joy: is ma a eigfoin

2023-04-20 12:46 UTC, Klausmd5 submitted a review, later dismissed
boah oida is des geil, passt auf jednvoi!!!!

2023-04-25 16:40 UTC, EinboeckFranz requested changes
Ihr kunnts nu des BountyCastle NuGet-Package updaten, donn is de Warning endlich weg

2023-04-25 16:40 UTC, EinboeckFranz commented on CODEOWNERS
> +deployment/builder.sh        @Klausmd5
Des File wiad glöscht

2023-04-25 17:53 UTC, EinboeckFranz commented
> boah oida is des geil, passt auf jednvoi!!!!

Aged like milk

2023-04-25 18:38 UTC, Klausmd5 commented on CODEOWNERS
> +deployment/builder.sh        @Klausmd5
Wuascht

2023-04-25 18:43 UTC, EinboeckFranz commented
> > Ihr kunnts nu des BountyCastle NuGet-Package updaten, donn is de Warning endlich weg
> 
> Wöche? Hobi eig jz eher weniger bock 

[Siehe do](https://discord.com/channels/489479881915236364/1021311502315171871/1089864277415968788)

2023-04-25 18:59 UTC, Klausmd5 commented
> > > Ihr kunnts nu des BountyCastle NuGet-Package updaten, donn is de Warning endlich weg
> > 
> > 
> > Wöche? Hobi eig jz eher weniger bock
> 
> [Siehe do](https://discord.com/channels/489479881915236364/1021311502315171871/1089864277415968788)

Aso, na des bast scho so. Des khead so sunst san de kritischn warnings bessa Sichtbar

2023-04-25 19:03 UTC, EinboeckFranz commented
> > > > Ihr kunnts nu des BountyCastle NuGet-Package updaten, donn is de Warning endlich weg
> > > 
> > > 
> > > Wöche? Hobi eig jz eher weniger bock
> > 
> > [Siehe do](https://discord.com/channels/489479881915236364/1021311502315171871/1089864277415968788)
> 
> Aso, na des bast scho so. Des khead so sunst san de kritischn warnings bessa Sichtbar 

🤌

2023-04-26 17:03 UTC, EinboeckFranz reviewed
Moi so a Frog, passt do evtl dazua:
Hobts ihr schomoi überlegt obs ned gscheida warad wonnts es des Port ändern vom Plugin-Frontend einfoch vorm Plugin startn mochts?

2023-04-26 17:04 UTC, EinboeckFranz commented
Sunst gibts nur oans zu sogn: "Einfoch geil"

2023-04-26 17:07 UTC, Klausmd5 commented
> Moi so a Frog, passt do evtl dazua: Hobts ihr schomoi überlegt obs ned gscheida warad wonnts es des Port ändern vom Plugin-Frontend einfoch vorm Plugin startn mochts?

ohne dasi jz irgn a ahnung davo hätt würd i moi behauptn des passiert e beim nx startn?

2023-04-26 17:08 UTC, Klausmd5 commented
> > > > > Ihr kunnts nu des BountyCastle NuGet-Package updaten, donn is de Warning endlich weg
> > > > 
> > > > 
> > > > Wöche? Hobi eig jz eher weniger bock
> > > 
> > > 
> > > [Siehe do](https://discord.com/channels/489479881915236364/1021311502315171871/1089864277415968788)
> > 
> > 
> > Aso, na des bast scho so. Des khead so sunst san de kritischn warnings bessa Sichtbar
> 
> 🤌

btw dafia miass ma dan nu ds submodule aufm template updaten damid dan üwaroi des neiche package drin is

2023-04-26 17:09 UTC, EinboeckFranz commented
> > Moi so a Frog, passt do evtl dazua: Hobts ihr schomoi überlegt obs ned gscheida warad wonnts es des Port ändern vom Plugin-Frontend einfoch vorm Plugin startn mochts?
> 
> ohne dasi jz irgn a ahnung davo hätt würd i moi behauptn des passiert e beim nx startn?

I hätt gmoant des is imma manuell gmocht woadn? @profiluefter

2023-04-26 17:25 UTC, profiluefter commented
> Moi so a Frog, passt do evtl dazua: Hobts ihr schomoi überlegt obs ned gscheida warad wonnts es des Port ändern vom Plugin-Frontend einfoch vorm Plugin startn mochts?

beim port ändern gehts moi grundsätzlich nur umdn angular dev server vom plugin frontend während da entwicklung
der port vom angular dev server muas in da mainframe dev config eitrogn sei wonn des do geh soid, somit is dynamisch ändern, wos glaub i des is wos du vorschlogst (und wos da devserver automatisch a vorschlogt wonn da port scho belegt is) eher schwierig

2023-04-26 17:31 UTC, EinboeckFranz commented
Jo ok donn lossn ma's

2023-04-26 17:31 UTC, EinboeckFranz approved these changes

2023-04-26 17:45 UTC, profiluefter commented
> > > Moi so a Frog, passt do evtl dazua: Hobts ihr schomoi überlegt obs ned gscheida warad wonnts es des Port ändern vom Plugin-Frontend einfoch vorm Plugin startn mochts?
> > 
> > 
> > ohne dasi jz irgn a ahnung davo hätt würd i moi behauptn des passiert e beim nx startn?
> 
> I hätt gmoant des is imma manuell gmocht woadn? @profiluefter

htl-grieskirchen-core/plugin-template#22 soite des thema eigentlich final erledigen

2023-04-26 17:50 UTC, merged