Create plugin interface project
htl-grieskirchen-core/core pull request #63
Opened 2022-10-10 10:51 UTC by SchneckchenAndy

Closes #46

2022-10-10 16:10 UTC, Klausmd5 requested changes
CI-Build Error: 
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/home/runner/work/core/core/Core.Plugin.Interface/Core.Plugin.Interface.csproj]

2022-10-10 16:12 UTC, profiluefter requested changes

2022-10-10 16:12 UTC, profiluefter commented on Core.Plugin.Interface/Core.Plugin.Interface.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
CI error because of: Wrong SDK for library only project
Compare with here: https://github.com/htl-grieskirchen-core/core/blob/develop/Core.Moodle.Interface/Core.Moodle.Interface.csproj#L1

2022-10-17 07:02 UTC, SchneckchenAndy commented on Core.Plugin.Interface/Core.Plugin.Interface.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Resolved in 99165b43c10286d9e3ff7f02b208868cbc6ea67f

2022-10-17 07:08 UTC, profiluefter commented on Core.Plugin.Interface/Core.Plugin.Interface.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Haut ned hi

2022-10-17 07:10 UTC, SchneckchenAndy commented on Core.Plugin.Interface/Core.Plugin.Interface.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Actually resolved in 798e6f9885383e1a2533d77afc85b6395ee0f4fb

2022-10-17 07:10 UTC, profiluefter submitted a review, later dismissed
foi geil

2022-10-17 07:15 UTC, merged

2022-12-12 17:15 UTC, profiluefter reviewed
ok